# Generated by Django 2.0b1 on 2017-10-29 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AppInfoKeyString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='Localizr.AppInfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinfokeystring_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keystring_creators', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keystring_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locale_creators', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locale_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizedString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizedstring_creators', to=settings.AUTH_USER_MODEL)),
                ('key_string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Localizr.KeyString')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizr.Locale')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizedstring_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appinfokeystring',
            name='key_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizr.KeyString'),
        ),
        migrations.AddField(
            model_name='appinfokeystring',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinfokeystring_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='base_locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizr.Locale'),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinfo_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appinfo_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='localizedstring',
            unique_together={('locale', 'key_string')},
        ),
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together={('name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='keystring',
            unique_together={('key',)},
        ),
        migrations.AlterUniqueTogether(
            name='appinfokeystring',
            unique_together={('app_info', 'key_string')},
        ),
        migrations.AlterUniqueTogether(
            name='appinfo',
            unique_together={('slug',)},
        ),
    ]
