# Generated by Django 2.0rc1 on 2017-11-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localizr', '0003_auto_20171123_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfo',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='appinfokeystring',
            options={'verbose_name': "App 's Key",
                     'verbose_name_plural': "App 's Keys"},
        ),
        migrations.AlterModelOptions(
            name='keystring',
            options={'verbose_name': 'Key', 'verbose_name_plural': 'Keys'},
        ),
        migrations.AlterModelOptions(
            name='locale',
            options={'verbose_name': 'Locale',
                     'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='localizedstring',
            options={'verbose_name': 'Localized String',
                     'verbose_name_plural': 'Localized Strings'},
        ),
    ]
