# Generated by Django 2.0rc1 on 2017-12-03 17:03

import apps.Localizr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Localizr', '0004_auto_20171129_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=36)),
                ('app_slug', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_creators', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
            },
        ),
        migrations.CreateModel(
            name='SnapshotFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('locale_code', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to=apps.Localizr.models.snapshot_folder)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshotfile_creators', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshotfile_modifiers', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='Localizr.Snapshot')),
            ],
            options={
                'verbose_name': 'SnapshotFile',
                'verbose_name_plural': 'SnapshotFiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='snapshotfile',
            unique_together={('snapshot', 'locale_code')},
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('key', 'app_slug', 'format')},
        ),
    ]
