# Generated by Django 2.0rc1 on 2017-12-04 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Localizr', '0006_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizr.AppInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appusergroup_creators', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appusergroup_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-Group-App Permission',
                'verbose_name_plural': 'User-Group-App Permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'User-App Permission', 'verbose_name_plural': 'User-App Permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='appuser',
            unique_together={('app_info', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='appusergroup',
            unique_together={('app_info', 'group')},
        ),
    ]
