# Generated by Django 2.0.1 on 2018-05-23 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localizr', '0009_localizedstring_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appinfo_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appinfo_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appinfokeystring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appinfokeystring_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appinfokeystring',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appinfokeystring_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appuser_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appuser_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appusergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appusergroup_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appusergroup',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appusergroup_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keystring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keystring_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keystring',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keystring_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locale_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locale',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locale_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localizedstring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizedstring_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localizedstring',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizedstring_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshotfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshotfile_creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshotfile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshotfile_modifiers', to=settings.AUTH_USER_MODEL),
        ),
    ]
