# Generated by Django 3.2.4 on 2021-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localizr', '0013_auto_20180717_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together=set(),
        ),
    ]
